spin_manifest_version = 2

[application]
name = "word-of-day"
version = "0.1.0"
authors = ["CreggEgg <eggcregg@gmail.com>"]
description = ""

[[trigger.http]]
route = "/..."
component = "word-of-day"

[component.word-of-day]
source = "target/wasm32-wasi/release/word_of_day.wasm"
key_value_stores = ["default"]
allowed_outbound_hosts = []
[component.word-of-day.build]
command = "cargo build --target wasm32-wasi --release"
watch = ["src/**/*.rs", "Cargo.toml"]

[variables]
kv_explorer_user = { required = true }
kv_explorer_password = { required = true }

[[trigger.http]]
component = "kv-explorer"
route = "/internal/kv-explorer/..."

[component.kv-explorer]
source = { url = "https://github.com/fermyon/spin-kv-explorer/releases/download/v0.10.0/spin-kv-explorer.wasm", digest = "sha256:65bc286f8315746d1beecd2430e178f539fa487ebf6520099daae09a35dbce1d" }
allowed_outbound_hosts = ["redis://*:*", "mysql://*:*", "postgres://*:*"]
# add or remove stores you want to explore here
key_value_stores = ["default"]

[component.kv-explorer.variables]
kv_credentials = "{{ kv_explorer_user }}:{{ kv_explorer_password }}"